development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: im1coolguy
  database: unit_converter 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: im1coolguy
  database: unit_converter_test 
